import { UserInfo } from "./types";
import { exchangeRatesInterface } from "./types";

export const userInfo: UserInfo[] = [
  {
    phone: "1234567890",
    firebase_id: "firebase_user_id_123",
    notification_permission: true,
    notification_token: "sample_notification_token",
    insta: {
      last_scrape: new Date(),
      id: "insta_user_id_123",
      access_token: "sample_insta_access_token",
      username: "johndoe",
      full_name: "John Doe",
      biography: "Learn coding with me!",
      profile_pic:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg",
      followers: 1000,
      following: 500,
      post_number: 50,
      average_like: 200,
      shared_posts: [
        {
          img: "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 223,
          comments: 11,
        },
        {
          img: "https://images.pexels.com/photos/89724/pexels-photo-89724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 240,
          comments: 13,
        },
        {
          img: "https://images.pexels.com/photos/102061/pexels-photo-102061.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 160,
          comments: 4,
        },
      ],
      keywords: ["javascript", "clean code"],
    },
    tiktok: {
      tiktok_last_scrape: new Date(),
      tiktok_average_like: 300,
      tiktok_engagement_rate: 0.05,
      tiktok_access_token: "sample_tiktok_access_token",
      tiktok_refresh_token: "sample_tiktok_refresh_token",
      open_id: "sample_open_id",
      refresh_expires_in: "3600",
      log_id: "sample_log_id",
      union_id: "sample_union_id",
      username: "johndoe",
      last_scrape: new Date(),
      followers: 2000,
      following: 1000,
      hearts: 5000,
      country: "UK",
      videos: [],
      profile_pic:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg",
      createTime: new Date(),
      privateAccount: false,
      verified: true,
      secret: false,
      tiktok_nickname: "johndoe",
      bio_description: "Developer tips and tricks!",
    },
    birthday: new Date("1990-01-01"),
    birthday_lastupdate: new Date(),
    age: new Date().getFullYear() - 1990,
    job: "Software Engineer",
    name: "John",
    surname: "Doe",
    score: 1000,
    email: "johndoe@example.com",
    gender: "Male",
    profile_complete: true,
    school_type: "University",
    school_name: "London University",
    city: "London",
    country: "UK",
    language: "English",
    money: {
      paparaAccountNo: 1234567890,
      current: 5000,
      currency: "USD",
      exchanges: [],
      city: "London",
      county: "UK",
      name: "John",
      surname: "Doe",
      id: "money_id_123",
      fee: 15,
    },
    hobbies: ["Coding", "Reading", "Swimming"],
    sharing_type: "Public",
    last_login: new Date(),
    applications_update: new Date(),
    hasNotificationPermission: true,
    onesignal_pushToken: "sample_onesignal_push_token",
    onesignal_userId: "sample_onesignal_user_id",
    currency: "USD",
    password: 123456,
    passwordTime: new Date(),
    verification: true,
    denied_verification: false,
    verification_last_action: new Date(),
    deleted: false,
    address: {
      contactName: "John Doe",
      contactPhone: "1234567890",
      city: "London",
      country: "UK",
      address: "123 Main Street",
      details: "Apartment 4B",
      zipCode: "12345",
      id: "address_id_123",
    },
    deviceInfo: {},
  },
  {
    phone: "4567890123",
    firebase_id: "firebase_user_id_456",
    notification_permission: true,
    notification_token: "sample_notification_token2",
    insta: {
      last_scrape: new Date(),
      id: "insta_user_id_456",
      access_token: "sample_insta_access_token2",
      username: "hesterhogan",
      full_name: "Hester Hogan",
      biography: "Dm me for collab! Model, influencer, yoga teacher, and more!",
      profile_pic:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-3_rxtqvi.jpg",
      followers: 15000,
      following: 100,
      post_number: 30,
      average_like: 8000,
      shared_posts: [
        {
          img: "https://images.pexels.com/photos/8436715/pexels-photo-8436715.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 9240,
          comments: 424,
        },
        {
          img: "https://images.pexels.com/photos/4046313/pexels-photo-4046313.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 7200,
          comments: 320,
        },
        {
          img: "https://images.pexels.com/photos/2426551/pexels-photo-2426551.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 8540,
          comments: 382,
        },
      ],
      keywords: ["asana", "yoga", "meditation"],
    },
    tiktok: {
      tiktok_last_scrape: new Date(),
      tiktok_average_like: 7000,
      tiktok_engagement_rate: 0.16,
      tiktok_access_token: "sample_tiktok_access_token2",
      tiktok_refresh_token: "sample_tiktok_refresh_token2",
      open_id: "sample_open_id2",
      refresh_expires_in: "3700",
      log_id: "sample_log_id2",
      union_id: "sample_union_id2",
      username: "hesterhogan",
      last_scrape: new Date(),
      followers: 4500,
      following: 50,
      hearts: 14000,
      country: "UK",
      videos: [],
      profile_pic:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-3_rxtqvi.jpg",
      createTime: new Date(),
      privateAccount: false,
      verified: true,
      secret: false,
      tiktok_nickname: "hesterhogan",
      bio_description: "Makeup, yoga, beauty, and more",
    },
    birthday: new Date("1994-03-05"),
    birthday_lastupdate: new Date(),
    age: new Date().getFullYear() - 1994,
    job: "Model",
    name: "Hester",
    surname: "Hogan",
    score: 2000,
    email: "hesterhogan@example.com",
    gender: "Female",
    profile_complete: true,
    school_type: "University",
    school_name: "Cambridge University",
    city: "Cambridge",
    country: "UK",
    language: "English",
    money: {
      paparaAccountNo: 4567890123,
      current: 45000,
      currency: "USD",
      exchanges: [],
      city: "Cambridge",
      county: "UK",
      name: "Hester",
      surname: "Hogan",
      id: "money_id_456",
      fee: 210,
    },
    hobbies: ["Makeup", "Yoga"],
    sharing_type: "Public",
    last_login: new Date(),
    applications_update: new Date(),
    hasNotificationPermission: true,
    onesignal_pushToken: "sample_onesignal_push_token2",
    onesignal_userId: "sample_onesignal_user_id2",
    currency: "USD",
    password: 456123,
    passwordTime: new Date(),
    verification: true,
    denied_verification: false,
    verification_last_action: new Date(),
    deleted: false,
    address: {
      contactName: "Hester Hogan",
      contactPhone: "4567890123",
      city: "Cambridge",
      country: "UK",
      address: "456 Main Street",
      details: "Apartment 4C",
      zipCode: "45612",
      id: "address_id_456",
    },
    deviceInfo: {},
  },
  {
    phone: "9876543210",
    firebase_id: "firebase_user_id_789",
    notification_permission: true,
    notification_token: "new_sample_notification_token",
    insta: {
      last_scrape: new Date(),
      id: "insta_user_id_789",
      access_token: "new_sample_insta_access_token",
      username: "janegardner",
      full_name: "Jane Gardner",
      biography: "Visit my website for products",
      profile_pic:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883334/person-1_rfzshl.jpg",
      followers: 1600,
      following: 600,
      post_number: 60,
      average_like: 250,
      shared_posts: [
        {
          img: "https://images.pexels.com/photos/1232131/pexels-photo-1232131.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 223,
          comments: 10,
        },
        {
          img: "https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 171,
          comments: 7,
        },
        {
          img: "https://images.pexels.com/photos/905844/pexels-photo-905844.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 365,
          comments: 12,
        },
      ],
      keywords: ["handmade", "gifts"],
    },
    tiktok: {
      tiktok_last_scrape: new Date(),
      tiktok_average_like: 350,
      tiktok_engagement_rate: 0.06,
      tiktok_access_token: "new_sample_tiktok_access_token",
      tiktok_refresh_token: "new_sample_tiktok_refresh_token",
      open_id: "new_sample_open_id",
      refresh_expires_in: "3600",
      log_id: "new_sample_log_id",
      union_id: "new_sample_union_id",
      username: "janegardner",
      last_scrape: new Date(),
      followers: 2500,
      following: 1200,
      hearts: 6000,
      country: "Canada",
      videos: [],
      profile_pic:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883334/person-1_rfzshl.jpg",
      createTime: new Date(),
      privateAccount: false,
      verified: true,
      secret: false,
      tiktok_nickname: "janegardner",
      bio_description: "Crafting!",
    },
    birthday: new Date("1985-05-15"),
    birthday_lastupdate: new Date(),
    age: new Date().getFullYear() - 1985,
    job: "Housewife",
    name: "Jane",
    surname: "Gardner",
    score: 1200,
    email: "janegardner@example.com",
    gender: "Female",
    profile_complete: true,
    school_type: "University",
    school_name: "Toronto University",
    city: "Toronto",
    country: "Canada",
    language: "English",
    money: {
      paparaAccountNo: 9876543210,
      current: 7000,
      currency: "CAD",
      exchanges: [],
      city: "Toronto",
      county: "Canada",
      name: "Jane",
      surname: "Doe",
      id: "money_id_789",
      fee: 60,
    },
    hobbies: ["Crafting", "Cooking"],
    sharing_type: "Public",
    last_login: new Date(),
    applications_update: new Date(),
    hasNotificationPermission: true,
    onesignal_pushToken: "new_sample_onesignal_push_token",
    onesignal_userId: "new_sample_onesignal_user_id",
    currency: "CAD",
    password: 987654,
    passwordTime: new Date(),
    verification: true,
    denied_verification: false,
    verification_last_action: new Date(),
    deleted: false,
    address: {
      contactName: "Jane Doe",
      contactPhone: "9876543210",
      city: "Toronto",
      country: "Canada",
      address: "456 Oak Avenue",
      details: "Suite 8C",
      zipCode: "67890",
      id: "new_address_id_789",
    },
    deviceInfo: {},
  },
  {
    phone: "5551234567",
    firebase_id: "firebase_user_id_034",
    notification_permission: true,
    notification_token: "turkish_sample_notification_token",
    insta: {
      last_scrape: new Date(),
      id: "insta_user_id_789",
      access_token: "turkish_sample_insta_access_token",
      username: "burakdurmaz",
      full_name: "Burak Durmaz",
      biography: "Visit our restaurant for delicious foods",
      profile_pic:
        "https://images.pexels.com/photos/3990502/pexels-photo-3990502.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      followers: 240000,
      following: 0,
      post_number: 70,
      average_like: 45000,
      shared_posts: [
        {
          img: "https://images.pexels.com/photos/618775/pexels-photo-618775.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 44124,
          comments: 1723,
        },
        {
          img: "https://images.pexels.com/photos/1154643/pexels-photo-1154643.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 52122,
          comments: 2435,
        },
        {
          img: "https://images.pexels.com/photos/2788792/pexels-photo-2788792.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          likes: 38018,
          comments: 1749,
        },
      ],
      keywords: ["chef", "food", "meat"],
    },
    tiktok: {
      tiktok_last_scrape: new Date(),
      tiktok_average_like: 50000,
      tiktok_engagement_rate: 0.23,
      tiktok_access_token: "turkish_sample_tiktok_access_token",
      tiktok_refresh_token: "turkish_sample_tiktok_refresh_token",
      open_id: "turkish_sample_open_id",
      refresh_expires_in: "3600",
      log_id: "turkish_sample_log_id",
      union_id: "turkish_sample_union_id",
      username: "burakdurmaz",
      last_scrape: new Date(),
      followers: 300000,
      following: 0,
      hearts: 800000,
      country: "Turkey",
      videos: [],
      profile_pic:
        "https://images.pexels.com/photos/3990502/pexels-photo-3990502.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      createTime: new Date(),
      privateAccount: false,
      verified: true,
      secret: false,
      tiktok_nickname: "burakdurmaz",
      bio_description: "Cooking is my passion!",
    },
    birthday: new Date("1980-07-25"),
    birthday_lastupdate: new Date(),
    age: new Date().getFullYear() - 1980,
    job: "Chef",
    name: "Burak",
    surname: "Durmaz",
    score: 7000,
    email: "burakdurmaz@example.com",
    gender: "Male",
    profile_complete: true,
    school_type: "High School",
    school_name: "Istanbul High School",
    city: "Istanbul",
    country: "Turkey",
    language: "Turkish",
    money: {
      paparaAccountNo: 5551234567,
      current: 1080000,
      currency: "TRY",
      exchanges: [],
      city: "İstanbul",
      county: "Turkey",
      name: "Burak",
      surname: "Durmaz",
      id: "turkish_money_id_789",
      fee: 30000,
    },
    hobbies: ["Cooking"],
    sharing_type: "Public",
    last_login: new Date(),
    applications_update: new Date(),
    hasNotificationPermission: true,
    onesignal_pushToken: "turkish_sample_onesignal_push_token",
    onesignal_userId: "turkish_sample_onesignal_user_id",
    currency: "USD",
    password: 349145,
    passwordTime: new Date(),
    verification: true,
    denied_verification: false,
    verification_last_action: new Date(),
    deleted: false,
    address: {
      contactName: "Burak Durmaz",
      contactPhone: "5551234567",
      city: "Istanbul",
      country: "Turkey",
      address: "789 Lezzet Sokak",
      details: "Kat 3, Daire 7",
      zipCode: "34567",
      id: "turkish_address_id_789",
    },
    deviceInfo: {},
  },
];

export const exchangeRates: exchangeRatesInterface = {
  USD: 1,
  CAD: 0.7,
  TRY: 0.04,
  GBP: 1.2,
};

export const collabs = [
  {
    img: "https://images.pexels.com/photos/8455314/pexels-photo-8455314.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    username: "@burakdurmaz",
    dealDate: new Date("2022-04-08"),
    dealType: "Post",
    dealWith: "Heinz",
    views: 1700100,
  },
  {
    img: "https://images.pexels.com/photos/7356375/pexels-photo-7356375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1s",
    username: "@hesterhogan",
    dealDate: new Date("2022-07-03"),
    dealType: "Post",
    dealWith: "Maybelline",
    views: 107000,
  },

  {
    img: "https://images.pexels.com/photos/276452/pexels-photo-276452.jpeg?auto=compress&cs=tinysrgb&w=1600",
    username: "@johndoe",
    dealDate: new Date("2023-01-03"),
    dealType: "Post",
    dealWith: "FreeCodeCamp",
    views: 4200,
  },
];
